export const NotificationTypes = {
  // Original
  BUDDY_REQUEST: "buddyRequest",
  BUDDY_ACCEPTED: "buddyAccepted",
  EVENT_INVITE: "eventInvite",
  EVENT_UPDATE: "eventUpdate",
  CHAT_MESSAGE: "chatMessage",
  SYSTEM_ALERT: "systemAlert",

  // Event notifications
  EVENT_RSVP_CONFIRMED: "EVENT_RSVP_CONFIRMED",
  NEW_EVENT_RSVP: "NEW_EVENT_RSVP",
  EVENT_TICKET_CONFIRMED: "EVENT_TICKET_CONFIRMED",
  NEW_EVENT_TICKET: "NEW_EVENT_TICKET",
  EVENT_RSVP_CANCELLED: "EVENT_RSVP_CANCELLED",
  STORE_CREATED: "STORE_CREATED",
  STORE_UPDATED: "STORE_UPDATED",

  // Upgrade
  UPGRADE_PROMPT: "upgrade_prompt",
  FEATURE_UPGRADE_PROMPT: "feature_upgrade_prompt",
  SUCCESS_UPGRADE_PROMPT: "success_upgrade_prompt",

  // Ask module
  ASK_CREATED: "ask_created",
  ASK_HELPFUL_MARKED: "ask_helpful_marked",
  ASK_FAVORITED: "ask_favorited",
  ASK_COMMENT_ADDED: "ask_comment_added",
  ASK_COMMENT_REPLY: "ask_comment_reply",
  ASK_MENTION: "ask_mention",

  // Jami engagement/email
  WELCOME_EMAIL: "WELCOME_EMAIL",
  PROFILE_REMINDER: "PROFILE_REMINDER",
  NEW_CONNECTION_REQUEST: "NEW_CONNECTION_REQUEST",
  CONNECTION_ACCEPTED: "CONNECTION_ACCEPTED",
  EVENT_REMINDER: "EVENT_REMINDER",
  NEW_EVENT: "NEW_EVENT",
  NEW_ITEM: "NEW_ITEM",
  WEEKLY_DIGEST: "WEEKLY_DIGEST",
  INACTIVE_USER: "INACTIVE_USER",
  PREMIUM_UPGRADE: "PREMIUM_UPGRADE",

  // Buddy
  CONNECTION_REQUEST: "connection_request",
  CONNECTION_ACCEPTED: "connection_accepted",
  USER_BLOCKED: "user_blocked",
  USER_UNBLOCKED: "user_unblocked",
  CONNECTION_REMOVED: "connection_removed",

  // Bump-specific
  BUMP_CREATED: "bump_created",
  BUMP_ACTIVATED: "bump_activated",
  BUMP_EXPIRED: "bump_expired",
  BUMP_ANALYTICS_REPORT: "bump_analytics_report",

  // Match system
  MATCH_CREATED: "match_created",
  MATCH_FOUND: "match_found",
  MATCH_BLOCKED: "match_blocked",

  // ---- PROFILE RELATED ----
  PROFILE_CREATED: "PROFILE_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_PICTURE_UPDATED: "PROFILE_PICTURE_UPDATED",
  PROFILE_VISIBILITY_CHANGED: "PROFILE_VISIBILITY_CHANGED",
  PROFILE_GALLERY_UPDATED: "PROFILE_GALLERY_UPDATED",

  // ------ User Auth
  // 📝 Registration
  USER_REGISTERED: "USER_REGISTERED",
  USER_SOCIAL_REGISTERED: "USER_SOCIAL_REGISTERED",

  // ✅ Verification
  VERIFICATION_SENT: "VERIFICATION_SENT",
  USER_VERIFIED: "USER_VERIFIED",

  // 🔑 Password
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",

  // 👤 Profile & Account
  PROFILE_PICTURE_UPDATED: "PROFILE_PICTURE_UPDATED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
};
