export const NotificationTypes = {
  // Buddy / Connections
  BUDDY_REQUEST: "BUDDY_REQUEST",
  BUDDY_ACCEPTED: "BUDDY_ACCEPTED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  CONNECTION_REMOVED: "CONNECTION_REMOVED",

  // Group / Community
  GROUP_CREATED: "GROUP_CREATED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_LEFT: "MEMBER_LEFT",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  JOIN_REQUEST_RECEIVED: "JOIN_REQUEST_RECEIVED",
  JOIN_REQUEST_APPROVED: "JOIN_REQUEST_APPROVED",
  JOIN_REQUEST_REJECTED: "JOIN_REQUEST_REJECTED",

  // Store / Marketplace
  STORE_CREATED: "STORE_CREATED",
  STORE_UPDATED: "STORE_UPDATED",
  STORE_DEACTIVATED: "STORE_DEACTIVATED",
  STORE_REACTIVATED: "STORE_REACTIVATED",
  STORE_DELETED: "STORE_DELETED",
  NEW_ITEM: "NEW_ITEM",

  // Game Matches
  MATCH_CREATED: "MATCH_CREATED",
  MATCH_FOUND: "MATCH_FOUND",
  MATCH_BLOCKED: "MATCH_BLOCKED",

  // Bump / Boosts
  BUMP_CREATED: "BUMP_CREATED",
  BUMP_ACTIVATED: "BUMP_ACTIVATED",
  BUMP_EXPIRED: "BUMP_EXPIRED",
  BUMP_ANALYTICS_REPORT: "BUMP_ANALYTICS_REPORT",

  // Upgrades / Premium Features
  UPGRADE_PROMPT: "UPGRADE_PROMPT",
  FEATURE_UPGRADE_PROMPT: "FEATURE_UPGRADE_PROMPT",
  SUCCESS_UPGRADE_PROMPT: "SUCCESS_UPGRADE_PROMPT",

  // User Auth
  USER_REGISTERED: "USER_REGISTERED",
  USER_SOCIAL_REGISTERED: "USER_SOCIAL_REGISTERED",
  VERIFICATION_SENT: "VERIFICATION_SENT",
  USER_VERIFIED: "USER_VERIFIED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",

  // Account Lifecycle
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ACCOUNT_PAUSED: "ACCOUNT_PAUSED",
  ACCOUNT_REACTIVATED: "ACCOUNT_REACTIVATED",
  ACCOUNT_DELETION_REQUESTED: "ACCOUNT_DELETION_REQUESTED",
  ACCOUNT_PERMANENTLY_DELETED: "ACCOUNT_PERMANENTLY_DELETED",

  // System Alerts
  SYSTEM_ALERT: "SYSTEM_ALERT",
  CHAT_MESSAGE: "CHAT_MESSAGE",
};
